wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1687543401.208606
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      - 74
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      - 74
      3:
      - 1
      - 19
      - 23
      4: 3.10.6
      5: 0.15.4
      8:
      - 1
      - 3
      - 5
encoder_name:
  desc: null
  value: efficientnet-b2
encoder_weights:
  desc: null
  value: imagenet
classes:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.0002
batch_size:
  desc: null
  value: 30
num_epochs:
  desc: null
  value: 1000
_items:
  desc: null
  value:
    _wandb: {}
    encoder_name: efficientnet-b2
    encoder_weights: imagenet
    classes: 1
    lr: 0.0002
    batch_size: 30
    num_epochs: 1000
_locked:
  desc: null
  value: {}
_users:
  desc: null
  value: {}
_users_inv:
  desc: null
  value: {}
_users_cnt:
  desc: null
  value: 0
_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_callback
_settings:
  desc: null
  value: '<Settings {''_args'': None, ''_aws_lambda'': False, ''_async_upload_concurrency_limit'':
    None, ''_cli_only_mode'': None, ''_colab'': False, ''_config_dict'': None, ''_console'':
    <SettingsConsole.WRAP: 1>, ''_cuda'': None, ''_disable_meta'': None, ''_disable_service'':
    False, ''_disable_stats'': None, ''_disable_viewer'': None, ''_except_exit'':
    True, ''_executable'': ''c:\\Users\\Ivan\\AppData\\Local\\Programs\\Python\\Python310\\python.exe'',
    ''_extra_http_headers'': None, ''_flow_control_custom'': False, ''_flow_control_disabled'':
    False, ''_internal_check_process'': 8, ''_internal_queue_timeout'': 2, ''_ipython'':
    False, ''_jupyter'': True, ''_jupyter_name'': None, ''_jupyter_path'': None, ''_jupyter_root'':
    None, ''_kaggle'': False, ''_live_policy_rate_limit'': None, ''_live_policy_wait_time'':
    None, ''_log_level'': None, ''_network_buffer'': None, ''_noop'': False, ''_notebook'':
    True, ''_offline'': False, ''_sync'': False, ''_os'': ''Windows-10-10.0.22621-SP0'',
    ''_platform'': ''windows'', ''_python'': ''3.10.6'', ''_runqueue_item_id'': None,
    ''_save_requirements'': True, ''_service_transport'': None, ''_service_wait'':
    30.0, ''_start_datetime'': datetime.datetime(2023, 6, 23, 20, 3, 21, 156562),
    ''_start_time'': 1687543401.1565616, ''_stats_pid'': 22124, ''_stats_sample_rate_seconds'':
    2.0, ''_stats_samples_to_average'': 15, ''_stats_join_assets'': True, ''_stats_neuron_monitor_config_path'':
    None, ''_stats_open_metrics_endpoints'': None, ''_stats_open_metrics_filters'':
    (''.*'',), ''_tmp_code_dir'': ''e:\\Ivan\\Desktop\\cv_notebook\\wandb\\run-20230623_200321-3eafgsad\\tmp\\code'',
    ''_tracelog'': None, ''_unsaved_keys'': None, ''_windows'': True, ''allow_val_change'':
    None, ''anonymous'': None, ''api_key'': ''***REDACTED***'', ''base_url'': ''https://api.wandb.ai'',
    ''code_dir'': None, ''config_paths'': None, ''console'': ''auto'', ''deployment'':
    ''cloud'', ''disable_code'': None, ''disable_git'': False, ''disable_hints'':
    None, ''disable_job_creation'': False, ''disabled'': False, ''docker'': None,
    ''email'': ''i.decosmis@studenti.uniba.it'', ''entity'': ''octopus-canneller'',
    ''files_dir'': ''e:\\Ivan\\Desktop\\cv_notebook\\wandb\\run-20230623_200321-3eafgsad\\files'',
    ''force'': None, ''git_commit'': None, ''git_remote'': ''origin'', ''git_remote_url'':
    None, ''git_root'': None, ''heartbeat_seconds'': 30, ''host'': ''DESKTOP-KD93HFE'',
    ''ignore_globs'': (), ''init_timeout'': 60.0, ''is_local'': False, ''job_source'':
    None, ''label_disable'': None, ''launch'': None, ''launch_config_path'': None,
    ''log_dir'': ''e:\\Ivan\\Desktop\\cv_notebook\\wandb\\run-20230623_200321-3eafgsad\\logs'',
    ''log_internal'': ''e:\\Ivan\\Desktop\\cv_notebook\\wandb\\run-20230623_200321-3eafgsad\\logs\\debug-internal.log'',
    ''log_symlink_internal'': ''e:\\Ivan\\Desktop\\cv_notebook\\wandb\\debug-internal.log'',
    ''log_symlink_user'': ''e:\\Ivan\\Desktop\\cv_notebook\\wandb\\debug.log'', ''log_user'':
    ''e:\\Ivan\\Desktop\\cv_notebook\\wandb\\run-20230623_200321-3eafgsad\\logs\\debug.log'',
    ''login_timeout'': None, ''magic'': None, ''mode'': ''online'', ''notebook_name'':
    None, ''problem'': ''fatal'', ''program'': ''<python with no main file>'', ''program_relpath'':
    None, ''project'': ''uncategorized'', ''project_url'': ''https://wandb.ai/octopus-canneller/uncategorized'',
    ''quiet'': None, ''reinit'': None, ''relogin'': None, ''resume'': None, ''resume_fname'':
    ''e:\\Ivan\\Desktop\\cv_notebook\\wandb\\wandb-resume.json'', ''resumed'': False,
    ''root_dir'': ''e:\\Ivan\\Desktop\\cv_notebook'', ''run_group'': None, ''run_id'':
    ''3eafgsad'', ''run_job_type'': None, ''run_mode'': ''run'', ''run_name'': ''usual-dust-346'',
    ''run_notes'': None, ''run_tags'': None, ''run_url'': ''https://wandb.ai/octopus-canneller/uncategorized/runs/3eafgsad'',
    ''sagemaker_disable'': None, ''save_code'': None, ''settings_system'': ''C:\\Users\\Ivan\\.config\\wandb\\settings'',
    ''settings_workspace'': ''e:\\Ivan\\Desktop\\cv_notebook\\wandb\\settings'', ''show_colors'':
    None, ''show_emoji'': None, ''show_errors'': True, ''show_info'': True, ''show_warnings'':
    True, ''silent'': False, ''start_method'': None, ''strict'': None, ''summary_errors'':
    None, ''summary_timeout'': 60, ''summary_warnings'': 5, ''sweep_id'': None, ''sweep_param_path'':
    None, ''sweep_url'': '''', ''symlink'': False, ''sync_dir'': ''e:\\Ivan\\Desktop\\cv_notebook\\wandb\\run-20230623_200321-3eafgsad'',
    ''sync_file'': ''e:\\Ivan\\Desktop\\cv_notebook\\wandb\\run-20230623_200321-3eafgsad\\run-3eafgsad.wandb'',
    ''sync_symlink_latest'': ''e:\\Ivan\\Desktop\\cv_notebook\\wandb\\latest-run'',
    ''system_sample'': 15, ''system_sample_seconds'': 2, ''table_raise_on_max_row_limit_exceeded'':
    False, ''timespec'': ''20230623_200321'', ''tmp_dir'': ''e:\\Ivan\\Desktop\\cv_notebook\\wandb\\run-20230623_200321-3eafgsad\\tmp'',
    ''username'': ''Ivan'', ''wandb_dir'': ''e:\\Ivan\\Desktop\\cv_notebook\\wandb\\''}>'
_artifact_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_artifact_callback
